### PR TITLE
Fix issue #53: Not printing ints and etc

### LINKED ISSUE #53: runtime.tty.print(): little problem
This is an issue I discovered while working with `runtime-node-net`. runtime's `runtime.tty.print()` function only accepts strings. You'd at least expect an error when given something else, but no. I tried printing an integer an nothing happened, no errors, nothing. Calling `toString()` on the number printed it. So I propose that the function should call `toString()` on the argument, which i'm believe is what `console.log()` does.

### PR DESCRIPTION
**Pull request by ArielAbreu**
Resolves minor problem where non-string values for text in exports.print would not be printed. Fixes #53

### CODE REVIEW

File: js/core/tty/terminal.js [hunk 1]
```diff
@@ -35,6 +35,9 @@ refresh();
 exports.color = vga.color;
 
 exports.print = function(text, repeat, fg, bg) {
+  // fix issue #53 where non-strings (ints, etc...) would not get printed
+  text = String(text);
```
Comment (piranna) [inline js/core/tty/terminal.js]: I think ```text = text.toString()``` is better, you are interested in the string literal, not a String object, and for string literals it will be returned itself instead of creating always an object...

Comment (iefserge) [inline js/core/tty/terminal.js]: @piranna `text = text.toString()` will fail if text is null/undefined. `String(expression)` converts any value to string, while `new String(expression)` creates an object

**Comment by iefserge** [comment]
@ArielAbreu looks good, thank you!

File: js/core/tty/terminal.js (hunk 1 above)
Comment (piranna) [inline js/core/tty/terminal.js]: > String(expression) converts any value to string

Ah, then it's ok :-)

**Comment by ArielAbreu** [comment]
No problem!
